# Generated by Django 4.1 on 2022-08-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.BigIntegerField()),
                ('crime_type_name', models.CharField(max_length=255)),
                ('report_date', models.DateTimeField(db_index=True)),
                ('call_date', models.DateTimeField()),
                ('offense_date', models.DateTimeField()),
                ('call_time', models.CharField(max_length=5)),
                ('call_datetime', models.DateTimeField()),
                ('disposition', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('agency_id', models.IntegerField()),
                ('address_type', models.CharField(max_length=255)),
                ('common_location', models.CharField(max_length=255)),
            ],
        ),
    ]
